### ISSUE TITLE
RaidAssist calling a nil value (SetColor) (error on load in)

### ISSUE THREAD

**Issue by Narillan** [Tercioo/RaidAssist#14]
4x RaidAssist\plugins\notes.lua:313: attempt to call method 'SetColor' (a nil value)
[string "@RaidAssist\plugins\notes.lua"]:313: in function `CreateNewLine'
[string "@RaidAssist\plugins\notes.lua"]:344: in function `UpdateBars'
[string "@RaidAssist\plugins\notes.lua"]:441: in function <RaidAssist\plugins\notes.lua:439>

Locals:
lineId = 1
line = RaidAssignmentsNoteEditboxScreenLine1 {
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 0 = <userdata>
}
xPosition = 0
progressBar = <table> {
 statusBar = DetailsFrameworkBarNumber441988 {
 }
 type = "timebar"
 HookList = <table> {
 }
 locked = false
 direction = "right"
 dframework = true
 widget = DetailsFrameworkBarNumber441988 {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 statusBar = DetailsFrameworkBarNumber441988 {
 }
 type = "timebar"
 HookList = <table> {
 }
 locked = false
 direction = "right"
 dframework = true
 widget = DetailsFrameworkBarNumber441988 {
 }
}
(*temporary) = 0.600000
(*temporary) = 0.600000
(*temporary) = 0.600000
(*temporary) = 0.800000
(*temporary) = "attempt to call method 'SetColor' (a nil value)"
f = RaidAssignmentsNoteEditboxScreen {
 0 = <userdata>
 fontSize = 12
 lineHeight = 16
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 barLines = <table> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 virtualScrollPosition = 1
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 UpdateBars = <function> defined @RaidAssist\plugins\notes.lua:335
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 CreateNewLine = <function> defined @RaidAssist\plugins\notes.lua:298
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
}
DetailsFramework = <table> {
 CooldownToClass = <table> {
 }
 ClassCache = <table> {
 }
 SavePositionOnScreen = <function> defined @RaidAssist\Libs\DF\panel.lua:2144
 CreateTabContainer = <function> defined @RaidAssist\Libs\DF\panel.lua:3912
 IsUnitTapDenied = <function> defined @RaidAssist\Libs\DF\fw.lua:4255
 CancelTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 NewLabel = <function> defined @RaidAssist\Libs\DF\label.lua:275
 SavedVars = <table> {
 }
 BuildStatusbarAuthorInfo = <function> defined @RaidAssist\Libs\DF\panel.lua:7006
 PanelCounter = 441988
 IconPick = <function> defined @RaidAssist\Libs

**Comment by Tercioo** [comment]
Fixed!
Thank you for reporting another bug, keep posting if you find more :)
