### ISSUE TITLE
RaidAssist/DBM interaction error?

### ISSUE THREAD

**Issue by Narillan** [Tercioo/RaidAssist#15]
Different issue that DeadlyBossMods let me know about: Showed up when we did a pull timer for The Terragrue. Thought it was a DBM error but it's referencing RaidAssist. 

Error while executing callback function: 00000127C7447D50 for event DBM_TimerStart: Interface\AddOns\RaidAssist\plugins\notes.lua: 160: attempt to index a nil value.

**Comment by Tercioo** [comment]
Fixed! 
Thank you for reporting!
